In [16]:
import pandas as pd
import numpy as np

raw = pd.read_csv('../data/raw/bremen.csv')

raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3585591 entries, 0 to 3585590
Data columns (total 14 columns):
 #   Column        Dtype  
---  ------        -----  
 0   Unnamed: 0    int64  
 1   p_spot        bool   
 2   p_place_type  int64  
 3   datetime      object 
 4   b_number      int64  
 5   trip          object 
 6   p_uid         int64  
 7   p_bikes       int64  
 8   p_lat         float64
 9   b_bike_type   int64  
 10  p_name        object 
 11  p_number      float64
 12  p_lng         float64
 13  p_bike        bool   
dtypes: bool(2), float64(3), int64(6), object(3)
memory usage: 335.1+ MB


In [11]:
raw.sample(5)

Unnamed: 0  p_spot  p_place_type             datetime  b_number  \
1470212     1470212    True             0  2019-09-27 00:00:00     42917   
527416       527416    True             0  2019-01-31 23:59:00     90133   
2532572     2532572   False            12  2019-06-10 23:59:00     20536   
1450556     1450556    True             0  2019-09-18 04:40:00    430323   
928965       928965   False            12  2019-10-23 23:59:00     90241   

          trip     p_uid  p_bikes      p_lat  b_bike_type  \
1470212  first    660978        6  49.508376           71   
527416    last     66150        5  49.429569            4   
2532572   last  17084330        1  53.070182           71   
1450556  start    339464        1  49.489012           71   
928965    last  23905884        1  49.460604           71   

                                           p_name  p_number      p_lng  p_bike  
1470212  Neckarstadt-Ost  - Carl-Zuckmayer-Straße    2536.0   8.476054   False  
527416                Südwestpark (Fitnessstudio)    4651.0  11.017651   False  
2532572                                BIKE 20536       0.0   8.790753    True  
1450556                              E4 - Rathaus    2512.0   8.462997   False  
928965                                 BIKE 90241       0.0  11.055309    True

In [7]:
raw['p_spot'].unique()

array([ True, False])

In [8]:
raw['p_place_type'].unique()

array([ 0, 12, 14,  3])

In [10]:
raw['trip'].unique()

array(['first', 'last', 'start', 'end'], dtype=object)

In [12]:
raw['p_bikes'].unique()

array([ 5,  4,  3,  1,  2,  0,  6,  7,  8, 11, 10,  9, 15, 14, 12, 13, 17,
       23, 20, 18, 22, 21, 16, 19, 24, 26, 25, 27, 28, 29, 30, 31, 32, 33,
       36, 35, 34, 38, 37, 39, 42, 43, 44, 40, 41, 47, 46, 48, 45, 49, 53,
       50, 54, 51, 52, 57, 60, 56, 64, 58, 61, 63, 62, 59, 55, 68, 69, 65,
       66, 67, 71, 70, 72])

In [13]:
raw['b_bike_type'].unique()

array([ 15,   0,   4,  71,  14, 120, 150,  17,  19,   5,  29])

In [14]:
raw['p_bike'].unique()

array([False,  True])